
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acv
 */
public class RoomSchedulerFrame extends javax.swing.JFrame
{

    
    /**
     * Creates new form RoomSchedulerFrame
     */
    public RoomSchedulerFrame()
    {
        super("Tiny College - Room Scheduler");
        initComponents();
        
        // Pre-loading all the data from the database
        rebuildFacultyComboBoxes();
        rebuildDateComboBoxes();
        rebuildRoomComboBoxes();
        rebuildReservationsComboBoxes();
        rewriteStatusWaitlistTextArea();
        
    }
    
    public void rebuildRoomComboBoxes(){
        dropRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel(RoomQueries.getAllRooms().toArray()));
    }
    
    public void rebuildReservationsComboBoxes(){ 
        try{
        String faculty = editReservationsFacultyComboBox.getSelectedItem().toString();        
        ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationsByFaculty(faculty);
        ArrayList<WaitlistEntry> waitlistEntries = WaitlistQueries.getWaitlistByFaculty(faculty);
        
        reservationsReservationsComboBox.setModel(new javax.swing.DefaultComboBoxModel(reservations.toArray()));
        reservationsWaitlistComboBox.setModel(new javax.swing.DefaultComboBoxModel(waitlistEntries.toArray()));
        }
        catch(NullPointerException e){
        }
    }
    
    public void rebuildFacultyComboBoxes()
    {
        ComboBoxModel faculty = new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray());
        reserveRoomFacultyComboBox.setModel(faculty);
        editReservationsFacultyComboBox.setModel(faculty);
        statusFacultyComboBox.setModel(faculty);
    }
    
    public void rebuildDateComboBoxes()
    {
        ComboBoxModel datesComboBox = new javax.swing.DefaultComboBoxModel(Dates.getDatesList().toArray());
        reserveRoomDateComboBox.setModel(datesComboBox);
        statusDateComboBox.setModel(datesComboBox);
    }
    
    
    public void rewriteStatusWaitlistTextArea(){
        statusWaitlistTextArea.setText(null);
        ArrayList<WaitlistEntry> waitlist; 
        waitlist = WaitlistQueries.getWaitlist();
        for(WaitlistEntry x : waitlist){            
            statusWaitlistTextArea.insert(x.toString() + "\n", 0);
        }
        statusWaitlistTextArea.insert("FACULTY \t DATE \t SEATS \n", 0);
    }

    public void rewriteStatusReservationTextArea(){
        statusReservationTextArea.setText(null);
        Date Date = (Date) statusDateComboBox.getSelectedItem();
        ArrayList<ReservationEntry> reservations;
        reservations = ReservationQueries.getReservationsByDate(Date);
        for(ReservationEntry REntry : reservations){
            statusReservationTextArea.insert(REntry.toString() + "\n", 0);
        }
        statusReservationTextArea.insert("FACULTY \t ROOM \t DATE \t SEATS \n", 0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        datePanel = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        addDateCombox = new javax.swing.JSpinner();
        addDateStatusLabel = new javax.swing.JLabel();
        addDateSubmitDate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addNewRoomNameTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        addRoomSpinner = new javax.swing.JSpinner();
        addNewRoomSubmit = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dropRoomComboBox = new javax.swing.JComboBox<>();
        dropRoomButton = new javax.swing.JButton();
        dropRoomStatusLabel1 = new javax.swing.JLabel();
        dropRoomStatusLabel2 = new javax.swing.JLabel();
        dropRoomStatusLabel3 = new javax.swing.JLabel();
        addRoomStatusLabel1 = new javax.swing.JLabel();
        addRoomStatusLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        reserveRoomFacultyComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        reserveRoomDateComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        reserveRoomSeatsTextField = new javax.swing.JTextField();
        reserveRoomSubmitButton = new javax.swing.JButton();
        reserveStatusLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        editFacultylabel = new javax.swing.JLabel();
        editReservationsFacultyComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        reservationsReservationsComboBox = new javax.swing.JComboBox<>();
        deleteReservationButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        deleteWaitlistButton = new javax.swing.JButton();
        reservationsWaitlistComboBox = new javax.swing.JComboBox<>();
        reservationsStatusLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addFacultyNameTextField = new javax.swing.JTextField();
        addFacultyNameSubmitButton = new javax.swing.JButton();
        addFacultyStatusLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        statusSelectDateLabel = new javax.swing.JLabel();
        statusDateComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusReservationTextArea = new javax.swing.JTextArea();
        waitingListStatusLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusWaitlistTextArea = new javax.swing.JTextArea();
        statusFacultyComboBox = new javax.swing.JComboBox<>();
        statusSelectFacultyLabel = new javax.swing.JLabel();
        statusChooseLabel = new javax.swing.JLabel();
        reservationStatusListLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Room Scheduler");

        datePanel.setBackground(new java.awt.Color(204, 255, 255));
        datePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        datePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        datePanel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setText("Add Date:");

        addDateCombox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        addDateCombox.setModel(new javax.swing.SpinnerDateModel());

        addDateStatusLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        addDateStatusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        addDateSubmitDate.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        addDateSubmitDate.setText("Submit");
        addDateSubmitDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateSubmitDateActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setText("Select Date to Add");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(addDateStatusLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(addDateCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addDateSubmitDate, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1346, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDateCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addDateStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDateSubmitDate)
                .addContainerGap(978, Short.MAX_VALUE))
        );

        datePanel.addTab("Add Date", jPanel4);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel15.setText("Add new room:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("New Room Name:");

        addNewRoomNameTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setText("New Room Size:");

        addRoomSpinner.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        addRoomSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        addNewRoomSubmit.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        addNewRoomSubmit.setText("Submit");
        addNewRoomSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewRoomSubmitActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel16.setText("Drop an existing room:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setText("Select Room to Drop:");

        dropRoomComboBox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        dropRoomButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        dropRoomButton.setText("Submit");
        dropRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropRoomButtonActionPerformed(evt);
            }
        });

        dropRoomStatusLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        dropRoomStatusLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dropRoomStatusLabel1.setPreferredSize(new java.awt.Dimension(45, 30));

        dropRoomStatusLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        dropRoomStatusLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dropRoomStatusLabel2.setPreferredSize(new java.awt.Dimension(45, 30));

        dropRoomStatusLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        dropRoomStatusLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dropRoomStatusLabel3.setPreferredSize(new java.awt.Dimension(45, 30));

        addRoomStatusLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        addRoomStatusLabel1.setPreferredSize(new java.awt.Dimension(45, 30));

        addRoomStatusLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        addRoomStatusLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addRoomStatusLabel2.setPreferredSize(new java.awt.Dimension(45, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addRoomStatusLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addNewRoomSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel10))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addNewRoomNameTextField)
                                    .addComponent(addRoomSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(dropRoomStatusLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(dropRoomStatusLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(39, 39, 39)
                                .addComponent(dropRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dropRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropRoomStatusLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addRoomStatusLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(856, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(addNewRoomNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(addRoomSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(addNewRoomSubmit)
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(dropRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dropRoomButton)
                .addGap(27, 27, 27)
                .addComponent(dropRoomStatusLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(dropRoomStatusLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dropRoomStatusLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(addRoomStatusLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(addRoomStatusLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );

        datePanel.addTab("Add/Drop Rooms", jPanel5);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Faculty: ");

        reserveRoomFacultyComboBox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        reserveRoomFacultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveRoomFacultyComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Date: ");

        reserveRoomDateComboBox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("Seats Required: ");

        reserveRoomSeatsTextField.setColumns(3);
        reserveRoomSeatsTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        reserveRoomSubmitButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        reserveRoomSubmitButton.setText("Submit");
        reserveRoomSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveRoomSubmitButtonActionPerformed(evt);
            }
        });

        reserveStatusLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        reserveStatusLabel.setText("   ");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reserveRoomSeatsTextField))
                            .addComponent(reserveRoomDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(45, 45, 45)
                                .addComponent(reserveRoomFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 848, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(539, 539, 539))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(reserveRoomSubmitButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(reserveStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reserveRoomFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel12)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(reserveRoomDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(reserveRoomSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(reserveRoomSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(reserveStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(791, Short.MAX_VALUE))
        );

        datePanel.addTab("Reserve Room", jPanel2);

        editFacultylabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        editFacultylabel.setText("Faculty:");

        editReservationsFacultyComboBox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        editReservationsFacultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editReservationsFacultyComboBoxActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setText("Reservations:");

        reservationsReservationsComboBox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        deleteReservationButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        deleteReservationButton.setText("Clear Reservation");
        deleteReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteReservationButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setText("Waitlist:");

        deleteWaitlistButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        deleteWaitlistButton.setText("Clear Waitlist Entry");
        deleteWaitlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteWaitlistButtonActionPerformed(evt);
            }
        });

        reservationsWaitlistComboBox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        reservationsStatusLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        reservationsStatusLabel.setText("    ");
        reservationsStatusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reservationsStatusLabel.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setText("Select Faculty");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reservationsWaitlistComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reservationsReservationsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(editFacultylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(61, 61, 61)
                            .addComponent(editReservationsFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(deleteWaitlistButton)
                    .addComponent(reservationsStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1200, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editFacultylabel)
                    .addComponent(editReservationsFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(reservationsReservationsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(deleteReservationButton)
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(reservationsWaitlistComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(deleteWaitlistButton)
                .addGap(39, 39, 39)
                .addComponent(reservationsStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(746, Short.MAX_VALUE))
        );

        datePanel.addTab("Edit Reservations & Waitlist", jPanel6);

        jPanel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel7.setText("Add new faculty ");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Faculty Name: ");

        addFacultyNameTextField.setColumns(20);
        addFacultyNameTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        addFacultyNameSubmitButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        addFacultyNameSubmitButton.setText("Submit");
        addFacultyNameSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyNameSubmitButtonActionPerformed(evt);
            }
        });

        addFacultyStatusLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        addFacultyStatusLabel.setText("    ");
        addFacultyStatusLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addFacultyStatusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(addFacultyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addFacultyNameSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFacultyStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addFacultyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addFacultyNameSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(addFacultyStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(942, Short.MAX_VALUE))
        );

        datePanel.addTab("Add Faculty", jPanel1);

        statusSelectDateLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        statusSelectDateLabel.setText("Date: ");
        statusSelectDateLabel.setToolTipText("");

        statusDateComboBox.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16));
        statusDateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusDateComboBoxActionPerformed(evt);
            }
        });

        statusReservationTextArea.setEditable(false);
        statusReservationTextArea.setColumns(20);
        statusReservationTextArea.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        statusReservationTextArea.setRows(5);
        jScrollPane2.setViewportView(statusReservationTextArea);

        waitingListStatusLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        waitingListStatusLabel.setText("Waiting Stats List:");

        statusWaitlistTextArea.setEditable(false);
        statusWaitlistTextArea.setColumns(20);
        statusWaitlistTextArea.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        statusWaitlistTextArea.setRows(5);
        jScrollPane1.setViewportView(statusWaitlistTextArea);

        statusFacultyComboBox.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16));
        statusFacultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFacultyComboBoxActionPerformed(evt);
            }
        });

        statusSelectFacultyLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        statusSelectFacultyLabel.setText("Faculty: ");

        statusChooseLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        statusChooseLabel.setText("Choose Date or Faculty ");

        reservationStatusListLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        reservationStatusListLabel.setText("Reservations Status List:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusSelectDateLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1009, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusChooseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(statusSelectFacultyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statusFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(reservationStatusListLabel))
                        .addGap(163, 163, 163)
                        .addComponent(waitingListStatusLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(statusDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusChooseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusSelectDateLabel)
                    .addComponent(statusDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusSelectFacultyLabel)
                    .addComponent(statusFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waitingListStatusLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reservationStatusListLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(571, Short.MAX_VALUE))
        );

        datePanel.addTab("Status by Date & Faculty", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFacultyNameSubmitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addFacultyNameSubmitButtonActionPerformed
    {//GEN-HEADEREND:event_addFacultyNameSubmitButtonActionPerformed
        // Add the faculty to the database.
        String name = addFacultyNameTextField.getText();
        Faculty.addFaculty(name);
        addFacultyStatusLabel.setText(name + " has been added to the Faculty Database.");

        reserveRoomFacultyComboBox.addItem(name);
    }//GEN-LAST:event_addFacultyNameSubmitButtonActionPerformed

    private void reserveRoomSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveRoomSubmitButtonActionPerformed
        String name = reserveRoomFacultyComboBox.getSelectedItem().toString();
        Date date = (Date) reserveRoomDateComboBox.getSelectedItem();
        int seats = Integer.parseInt(reserveRoomSeatsTextField.getText());
        ReservationEntry entry = new ReservationEntry(name, date, seats);
        if(entry.getRoom() != null){
            reserveStatusLabel.setText(entry.getFaculty()+ " reserved for " + 
                    entry.getRoom() + " at " + date);
        } else {
            reserveStatusLabel.setText(" Rooms are occupied !!! " + " you have been"
                    + " waitlisted on " + date);
        }
        rewriteStatusReservationTextArea();
        rewriteStatusWaitlistTextArea();       
        rebuildReservationsComboBoxes();
    }//GEN-LAST:event_reserveRoomSubmitButtonActionPerformed

    private void statusDateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusDateComboBoxActionPerformed
        rewriteStatusReservationTextArea();
        rewriteStatusWaitlistTextArea();
    }//GEN-LAST:event_statusDateComboBoxActionPerformed

    private void addDateSubmitDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateSubmitDateActionPerformed
        // Convert Date to useable format, then add it
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String spinnerValue = formater.format(addDateCombox.getValue());
        Date day = Date.valueOf(spinnerValue);       
        Dates.addDate(day.toString());
        addDateStatusLabel.setText(day.toString() + " added");
        
        rebuildDateComboBoxes();
    }//GEN-LAST:event_addDateSubmitDateActionPerformed

    private void addNewRoomSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRoomSubmitActionPerformed

        String roomNameInputted = addNewRoomNameTextField.getText();
        int roomSizeInputted = Integer.parseInt(addRoomSpinner.getValue().toString());
        RoomEntry room = new RoomEntry(roomNameInputted, roomSizeInputted);        
        RoomQueries.addRoom(room);
        ArrayList<ReservationEntry> reservationsList = ReservationQueries.getReservationsByRoom(roomNameInputted);
        addRoomStatusLabel1.setText(roomNameInputted +" with " + roomSizeInputted + " seats is added");        
        String newReservationsString = "";
        if(!reservationsList.isEmpty())
            {
                for(ReservationEntry Rentry : reservationsList)
                {
                    newReservationsString += Rentry.getFaculty() + " has reserved the new room for " + Rentry.getDate() + " \n, ";
                }
            addRoomStatusLabel2.setText(newReservationsString);
            }
        rewriteStatusWaitlistTextArea();
        rewriteStatusReservationTextArea();
        rebuildRoomComboBoxes();
        rebuildReservationsComboBoxes();     
    }//GEN-LAST:event_addNewRoomSubmitActionPerformed

    private void deleteReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteReservationButtonActionPerformed
        
        ReservationEntry reservationList = (ReservationEntry) reservationsReservationsComboBox.getSelectedItem();
        ReservationQueries.deleteReservationEntry(reservationList);
        WaitlistQueries.rebuildWaitlist();
        int check = 0;
        ArrayList<ReservationEntry> newReservations = ReservationQueries.getReservationsByDate(reservationList.getDate());
        for(ReservationEntry Rentry : newReservations)
        {            
            if(Rentry.getRoom().equals((reservationList.getRoom())))
            {
                reservationsStatusLabel.setText(" Selected Reservation Cancelled Successfully..., Room is now assigned to " + Rentry.getFaculty());
                check++;
            }            
        }       
        if(check == 0)
        {
            reservationsStatusLabel.setText("Selected Resrvation Cancelled Successfully.... Room is not suitable for anyone on waitlist");
        } 
        rewriteStatusWaitlistTextArea();
        rewriteStatusReservationTextArea();
        rebuildReservationsComboBoxes();
        
    }//GEN-LAST:event_deleteReservationButtonActionPerformed

    private void deleteWaitlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteWaitlistButtonActionPerformed
        // Delete selected waitlist entry
        WaitlistEntry waitlist = (WaitlistEntry) reservationsWaitlistComboBox.getSelectedItem();
        
        WaitlistQueries.deleteWaitlistEntry(waitlist);
        
        reservationsStatusLabel.setText("The selected waitlist entry was deleted");
        
        rebuildReservationsComboBoxes();
        rewriteStatusWaitlistTextArea();
    }//GEN-LAST:event_deleteWaitlistButtonActionPerformed

    private void dropRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropRoomButtonActionPerformed
        
        try{
        // Drop the room selected by the user
        RoomEntry room = (RoomEntry) dropRoomComboBox.getSelectedItem();
        ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationsByRoom(room.getName());
                
        RoomQueries.dropRoom(room);
        dropRoomStatusLabel1.setText(room + " has been dropped");
        
        //Split list into those who were added to reservations and those who weren't
        ArrayList<String> reserved = new ArrayList<String>();
        ArrayList<String> waitlisted = new ArrayList<String>();
        
        for(ReservationEntry x : reservations){
            ArrayList<ReservationEntry> facultyReservation = ReservationQueries.getReservationsByFaculty(x.getFaculty());
            int length = reserved.size();
            
            for(ReservationEntry e: facultyReservation){
                if(x.getDate().equals(e.getDate())){
                    reserved.add(x.getFaculty());
                }
            }
            
            if(reserved.size() == length)
                waitlisted.add(x.getFaculty());
        }
        
        int reservedLength = reserved.toString().length();
        int waitlistedLength = waitlisted.toString().length();
        
        
        if(reserved.isEmpty())
            dropRoomStatusLabel2.setText("No one reserved a new room");
        else
            dropRoomStatusLabel2.setText(reserved.toString().substring(1, reservedLength-1) + " has been reserved to a new room");
        
        
        if(waitlisted.isEmpty())
            dropRoomStatusLabel3.setText("No one added to the waitlist");
        else
            dropRoomStatusLabel3.setText(waitlisted.toString().substring(1, waitlistedLength-1) + " has been added to the current waitlist");
        
        
        rebuildRoomComboBoxes();
        rebuildReservationsComboBoxes();
        rewriteStatusWaitlistTextArea();
        rewriteStatusReservationTextArea();
        }
        catch(NullPointerException e){
        }
    }//GEN-LAST:event_dropRoomButtonActionPerformed

    private void editReservationsFacultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editReservationsFacultyComboBoxActionPerformed
        rebuildReservationsComboBoxes();
        reservationsStatusLabel.setText(null);
    }//GEN-LAST:event_editReservationsFacultyComboBoxActionPerformed

    private void statusFacultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFacultyComboBoxActionPerformed
        try{
            String faculty = statusFacultyComboBox.getSelectedItem().toString();
            ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationsByFaculty(faculty);
            ArrayList<WaitlistEntry> waitlistEntries = WaitlistQueries.getWaitlistByFaculty(faculty);
            statusReservationTextArea.setText(null);
            statusWaitlistTextArea.setText(null);

            for(ReservationEntry x : reservations){
                statusReservationTextArea.insert(x.toString() + "\n", 0);
            }

            statusReservationTextArea.insert("FACULTY \t ROOM \t DATE \t SEATS \n", 0);

            for(WaitlistEntry x : waitlistEntries){
                statusWaitlistTextArea.insert(x.toString() + "\n", 0);
            }

            statusWaitlistTextArea.insert("FACULTY \t DATE \t SEATS \n", 0);

        }
        catch(NullPointerException e){
        }
    }//GEN-LAST:event_statusFacultyComboBoxActionPerformed

    private void reserveRoomFacultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveRoomFacultyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveRoomFacultyComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RoomSchedulerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner addDateCombox;
    private javax.swing.JLabel addDateStatusLabel;
    private javax.swing.JButton addDateSubmitDate;
    private javax.swing.JButton addFacultyNameSubmitButton;
    private javax.swing.JTextField addFacultyNameTextField;
    private javax.swing.JLabel addFacultyStatusLabel;
    private javax.swing.JTextField addNewRoomNameTextField;
    private javax.swing.JButton addNewRoomSubmit;
    private javax.swing.JSpinner addRoomSpinner;
    private javax.swing.JLabel addRoomStatusLabel1;
    private javax.swing.JLabel addRoomStatusLabel2;
    private javax.swing.JTabbedPane datePanel;
    private javax.swing.JButton deleteReservationButton;
    private javax.swing.JButton deleteWaitlistButton;
    private javax.swing.JButton dropRoomButton;
    private javax.swing.JComboBox<String> dropRoomComboBox;
    private javax.swing.JLabel dropRoomStatusLabel1;
    private javax.swing.JLabel dropRoomStatusLabel2;
    private javax.swing.JLabel dropRoomStatusLabel3;
    private javax.swing.JLabel editFacultylabel;
    private javax.swing.JComboBox<String> editReservationsFacultyComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel reservationStatusListLabel;
    private javax.swing.JComboBox<String> reservationsReservationsComboBox;
    private javax.swing.JLabel reservationsStatusLabel;
    private javax.swing.JComboBox<String> reservationsWaitlistComboBox;
    private javax.swing.JComboBox<String> reserveRoomDateComboBox;
    private javax.swing.JComboBox<String> reserveRoomFacultyComboBox;
    private javax.swing.JTextField reserveRoomSeatsTextField;
    private javax.swing.JButton reserveRoomSubmitButton;
    private javax.swing.JLabel reserveStatusLabel;
    private javax.swing.JLabel statusChooseLabel;
    private javax.swing.JComboBox<String> statusDateComboBox;
    private javax.swing.JComboBox<String> statusFacultyComboBox;
    private javax.swing.JTextArea statusReservationTextArea;
    private javax.swing.JLabel statusSelectDateLabel;
    private javax.swing.JLabel statusSelectFacultyLabel;
    private javax.swing.JTextArea statusWaitlistTextArea;
    private javax.swing.JLabel waitingListStatusLabel;
    // End of variables declaration//GEN-END:variables
}
